language: cpp
matrix:
  include:
  - os: linux
    sudo: true
    dist: trusty
  - os: osx
    sudo: false
env:
  global:
  - ENCRYPTION_LABEL: c43c54d4c8e0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - qt5-default
    - libqt5opengl5-dev
    - xorg-dev
    - lib32stdc++6
    - lftp
install: "./.travis-deps.sh"
script: "./.travis-build.sh"
after_success: "./.travis-upload.sh"
